name: Deploy Astro to VPS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'  # 更改为 pnpm 缓存

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest  # 使用最新版本 pnpm

      - name: Install dependencies
        run: pnpm install  # 使用 pnpm 安装依赖

      - name: Build project
        run: pnpm run build  # 使用 pnpm 构建项目

      - name: Check dist directory
        run: |
          echo "=== 检查 dist 目录 ==="
          ls -la
          if [ -d "dist" ]; then
            echo "✅ dist 目录存在"
            ls -la dist/
            echo "=== dist 目录内容 ==="
            find dist/ -type f | head -20
          else
            echo "❌ dist 目录不存在"
            exit 1
          fi

      - name: Deploy dist to VPS
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: ${{ secrets.VPS_SITE_PATH }}
          SOURCE: "dist/"  # Astro 静态输出目录
          ARGS: "-avz --delete"