name: Deploy Astro Site to GitHub Pages (npm)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Verify npm & node
        run: |
          node -v
          npm -v

      - name: Allow non-strict engines (avoid EBADENGINE fatal)
        run: npm config set engine-strict false

      - name: Install dependencies (npm)
        # 用 npm install 而不是 npm ci，避免 lockfile 不一致中断流程
        run: npm install --no-audit --no-fund

      - name: Build site
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2